from enum import Enum


class Language(Enum):
    AA = {'full_name': 'Afar', 'short_name': 'aa', 'local_name': 'Afar'}
    AB = {'full_name': 'Abkhazian', 'short_name': 'ab', 'local_name': 'Аҧсуа'}
    AF = {'full_name': 'Afrikaans', 'short_name': 'af', 'local_name': 'Afrikaans'}
    AK = {'full_name': 'Akan', 'short_name': 'ak', 'local_name': 'Akana'}
    ALS = {'full_name': 'Alemannic', 'short_name': 'als', 'local_name': 'Alemannisch'}
    AM = {'full_name': 'Amharic', 'short_name': 'am', 'local_name': 'አማርኛ'}
    AN = {'full_name': 'Aragonese', 'short_name': 'an', 'local_name': 'Aragonés'}
    ANG = {'full_name': 'Angal', 'short_name': 'ang', 'local_name': 'Angal Heneng'}
    ANG1 = {'full_name': 'Anglo-Saxon / Old English', 'short_name': 'ang1', 'local_name': 'Englisc'}
    AR = {'full_name': 'Arabic', 'short_name': 'ar', 'local_name': 'العربية'}
    ARC = {'full_name': 'Aramaic', 'short_name': 'arc', 'local_name': 'ܣܘܪܬ'}
    AS = {'full_name': 'Assamese', 'short_name': 'as', 'local_name': 'অসমীয়া'}
    AST = {'full_name': 'Asturian', 'short_name': 'ast', 'local_name': 'Asturianu'}
    AV = {'full_name': 'Avar', 'short_name': 'av', 'local_name': 'Авар'}
    AWA = {'full_name': 'Awadhi', 'short_name': 'awa', 'local_name': 'Awadhi'}
    AY = {'full_name': 'Aymara', 'short_name': 'ay', 'local_name': 'Aymar'}
    AZ = {'full_name': 'Azerbaijani', 'short_name': 'az', 'local_name': 'Azərbaycanca / آذربايجان'}
    BA = {'full_name': 'Bashkir', 'short_name': 'ba', 'local_name': 'Башҡорт'}
    BAR = {'full_name': 'Bavarian', 'short_name': 'bar', 'local_name': 'Boarisch'}
    BAT_SMG = {'full_name': 'Samogitian', 'short_name': 'bat-smg', 'local_name': 'Žemaitėška'}
    BCL = {'full_name': 'Bikol', 'short_name': 'bcl', 'local_name': 'Bikol Central'}
    BE = {'full_name': 'Belarusian', 'short_name': 'be', 'local_name': 'Беларуская'}
    BE_X_OLD = {'full_name': 'Belarusian (Taraškievica)', 'short_name': 'be-x-old',
                'local_name': 'Беларуская (тарашкевіца)'}
    BG = {'full_name': 'Bulgarian', 'short_name': 'bg', 'local_name': 'Български'}
    BH = {'full_name': 'Bihari', 'short_name': 'bh', 'local_name': 'भोजपुरी'}
    BI = {'full_name': 'Bislama', 'short_name': 'bi', 'local_name': 'Bislama'}
    BM = {'full_name': 'Bambara', 'short_name': 'bm', 'local_name': 'Bamanankan'}
    BN = {'full_name': 'Bengali', 'short_name': 'bn', 'local_name': 'বাংলা'}
    BO = {'full_name': 'Tibetan', 'short_name': 'bo', 'local_name': 'བོད་ཡིག / Bod skad'}
    BPY = {'full_name': 'Bishnupriya Manipuri', 'short_name': 'bpy', 'local_name': 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী'}
    BR = {'full_name': 'Breton', 'short_name': 'br', 'local_name': 'Brezhoneg'}
    BS = {'full_name': 'Bosnian', 'short_name': 'bs', 'local_name': 'Bosanski'}
    BUG = {'full_name': 'Buginese', 'short_name': 'bug', 'local_name': 'ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi'}
    BXR = {'full_name': 'Buriat (Russia)', 'short_name': 'bxr', 'local_name': 'Буряад хэлэн'}
    CA = {'full_name': 'Catalan', 'short_name': 'ca', 'local_name': 'Català'}
    CDO = {'full_name': 'Min Dong Chinese', 'short_name': 'cdo', 'local_name': 'Mìng-dĕ̤ng-ngṳ̄ / 閩東語'}
    CE = {'full_name': 'Chechen', 'short_name': 'ce', 'local_name': 'Нохчийн'}
    CEB = {'full_name': 'Cebuano', 'short_name': 'ceb', 'local_name': 'Sinugboanong Binisaya'}
    CH = {'full_name': 'Chamorro', 'short_name': 'ch', 'local_name': 'Chamoru'}
    CHO = {'full_name': 'Choctaw', 'short_name': 'cho', 'local_name': 'Choctaw'}
    CHR = {'full_name': 'Cherokee', 'short_name': 'chr', 'local_name': 'ᏣᎳᎩ'}
    CHY = {'full_name': 'Cheyenne', 'short_name': 'chy', 'local_name': 'Tsetsêhestâhese'}
    CKB = {'full_name': 'Kurdish (Sorani)', 'short_name': 'ckb', 'local_name': 'کوردی'}
    CO = {'full_name': 'Corsican', 'short_name': 'co', 'local_name': 'Corsu'}
    CR = {'full_name': 'Cree', 'short_name': 'cr', 'local_name': 'Nehiyaw'}
    CS = {'full_name': 'Czech', 'short_name': 'cs', 'local_name': 'Česky'}
    CSB = {'full_name': 'Kashubian', 'short_name': 'csb', 'local_name': 'Kaszëbsczi'}
    CU = {'full_name': 'Old Church Slavonic / Old Bulgarian', 'short_name': 'cu', 'local_name': 'словѣньскъ / slověnĭskŭ'}
    CV = {'full_name': 'Chuvash', 'short_name': 'cv', 'local_name': 'Чăваш'}
    CY = {'full_name': 'Welsh', 'short_name': 'cy', 'local_name': 'Cymraeg'}
    DA = {'full_name': 'Danish', 'short_name': 'da', 'local_name': 'Dansk'}
    DE = {'full_name': 'German', 'short_name': 'de', 'local_name': 'Deutsch'}
    DIQ = {'full_name': 'Dimli', 'short_name': 'diq', 'local_name': 'Zazaki'}
    DSB = {'full_name': 'Lower Sorbian', 'short_name': 'dsb', 'local_name': 'Dolnoserbski'}
    DV = {'full_name': 'Divehi', 'short_name': 'dv', 'local_name': 'ދިވެހިބަސް'}
    DZ = {'full_name': 'Dzongkha', 'short_name': 'dz', 'local_name': 'ཇོང་ཁ'}
    EE = {'full_name': 'Ewe', 'short_name': 'ee', 'local_name': 'Ɛʋɛ'}
    EL = {'full_name': 'Greek', 'short_name': 'el', 'local_name': 'Ελληνικά'}
    EN = {'full_name': 'English', 'short_name': 'en', 'local_name': 'English'}
    EO = {'full_name': 'Esperanto', 'short_name': 'eo', 'local_name': 'Esperanto'}
    ES = {'full_name': 'Spanish', 'short_name': 'es', 'local_name': 'Español'}
    ET = {'full_name': 'Estonian', 'short_name': 'et', 'local_name': 'Eesti'}
    EU = {'full_name': 'Basque', 'short_name': 'eu', 'local_name': 'Euskara'}
    EXT = {'full_name': 'Extremaduran', 'short_name': 'ext', 'local_name': 'Estremeñu'}
    FA = {'full_name': 'Persian', 'short_name': 'fa', 'local_name': 'فارسی'}
    FF = {'full_name': 'Peul', 'short_name': 'ff', 'local_name': 'Fulfulde'}
    FI = {'full_name': 'Finnish', 'short_name': 'fi', 'local_name': 'Suomi'}
    FIU_VRO = {'full_name': 'Võro', 'short_name': 'fiu-vro', 'local_name': 'Võro'}
    FJ = {'full_name': 'Fijian', 'short_name': 'fj', 'local_name': 'Na Vosa Vakaviti'}
    FO = {'full_name': 'Faroese', 'short_name': 'fo', 'local_name': 'Føroyskt'}
    FR = {'full_name': 'French', 'short_name': 'fr', 'local_name': 'Français'}
    FRP = {'full_name': 'Arpitan / Franco-Provençal', 'short_name': 'frp', 'local_name': 'Arpitan / francoprovençal'}
    FUR = {'full_name': 'Friulian', 'short_name': 'fur', 'local_name': 'Furlan'}
    FY = {'full_name': 'West Frisian', 'short_name': 'fy', 'local_name': 'Frysk'}
    GA = {'full_name': 'Irish', 'short_name': 'ga', 'local_name': 'Gaeilge'}
    GAN = {'full_name': 'Gan Chinese', 'short_name': 'gan', 'local_name': '贛語'}
    GBM = {'full_name': 'Garhwali', 'short_name': 'gbm', 'local_name': 'गढ़वळी'}
    GD = {'full_name': 'Scottish Gaelic', 'short_name': 'gd', 'local_name': 'Gàidhlig'}
    GIL = {'full_name': 'Gilbertese', 'short_name': 'gil', 'local_name': 'Taetae ni kiribati'}
    GL = {'full_name': 'Galician', 'short_name': 'gl', 'local_name': 'Galego'}
    GN = {'full_name': 'Guarani', 'short_name': 'gn', 'local_name': 'Avañe\'ẽ'}
    GOT = {'full_name': 'Gothic', 'short_name': 'got', 'local_name': 'gutisk'}
    GU = {'full_name': 'Gujarati', 'short_name': 'gu', 'local_name': 'ગુજરાતી'}
    GV = {'full_name': 'Manx', 'short_name': 'gv', 'local_name': 'Gaelg'}
    HA = {'full_name': 'Hausa', 'short_name': 'ha', 'local_name': 'هَوُسَ'}
    HAK = {'full_name': 'Hakka Chinese', 'short_name': 'hak', 'local_name': '客家語/Hak-kâ-ngî'}
    HAW = {'full_name': 'Hawaiian', 'short_name': 'haw', 'local_name': 'Hawai`i'}
    HE = {'full_name': 'Hebrew', 'short_name': 'he', 'local_name': 'עברית'}
    HI = {'full_name': 'Hindi', 'short_name': 'hi', 'local_name': 'हिन्दी'}
    HO = {'full_name': 'Hiri Motu', 'short_name': 'ho', 'local_name': 'Hiri Motu'}
    HR = {'full_name': 'Croatian', 'short_name': 'hr', 'local_name': 'Hrvatski'}
    HT = {'full_name': 'Haitian', 'short_name': 'ht', 'local_name': 'Krèyol ayisyen'}
    HU = {'full_name': 'Hungarian', 'short_name': 'hu', 'local_name': 'Magyar'}
    HY = {'full_name': 'Armenian', 'short_name': 'hy', 'local_name': 'Հայերեն'}
    HZ = {'full_name': 'Herero', 'short_name': 'hz', 'local_name': 'Otsiherero'}
    IA = {'full_name': 'Interlingua', 'short_name': 'ia', 'local_name': 'Interlingua'}
    ID = {'full_name': 'Indonesian', 'short_name': 'id', 'local_name': 'Bahasa Indonesia'}
    IE = {'full_name': 'Interlingue', 'short_name': 'ie', 'local_name': 'Interlingue'}
    IG = {'full_name': 'Igbo', 'short_name': 'ig', 'local_name': 'Igbo'}
    II = {'full_name': 'Sichuan Yi', 'short_name': 'ii', 'local_name': 'ꆇꉙ / 四川彝语'}
    IK = {'full_name': 'Inupiak', 'short_name': 'ik', 'local_name': 'Iñupiak'}
    ILO = {'full_name': 'Ilokano', 'short_name': 'ilo', 'local_name': 'Ilokano'}
    INH = {'full_name': 'Ingush', 'short_name': 'inh', 'local_name': 'ГӀалгӀай'}
    IO = {'full_name': 'Ido', 'short_name': 'io', 'local_name': 'Ido'}
    IS = {'full_name': 'Icelandic', 'short_name': 'is', 'local_name': 'Íslenska'}
    IT = {'full_name': 'Italian', 'short_name': 'it', 'local_name': 'Italiano'}
    IU = {'full_name': 'Inuktitut', 'short_name': 'iu', 'local_name': 'ᐃᓄᒃᑎᑐᑦ'}
    JA = {'full_name': 'Japanese', 'short_name': 'ja', 'local_name': '日本語'}
    JBO = {'full_name': 'Lojban', 'short_name': 'jbo', 'local_name': 'Lojban'}
    JV = {'full_name': 'Javanese', 'short_name': 'jv', 'local_name': 'Basa Jawa'}
    KA = {'full_name': 'Georgian', 'short_name': 'ka', 'local_name': 'ქართული'}
    KG = {'full_name': 'Kongo', 'short_name': 'kg', 'local_name': 'KiKongo'}
    KI = {'full_name': 'Kikuyu', 'short_name': 'ki', 'local_name': 'Gĩkũyũ'}
    KJ = {'full_name': 'Kuanyama', 'short_name': 'kj', 'local_name': 'Kuanyama'}
    KK = {'full_name': 'Kazakh', 'short_name': 'kk', 'local_name': 'Қазақша'}
    KL = {'full_name': 'Greenlandic', 'short_name': 'kl', 'local_name': 'Kalaallisut'}
    KM = {'full_name': 'Cambodian', 'short_name': 'km', 'local_name': 'ភាសាខ្មែរ'}
    KN = {'full_name': 'Kannada', 'short_name': 'kn', 'local_name': 'ಕನ್ನಡ'}
    KHW = {'full_name': 'Khowar', 'short_name': 'khw', 'local_name': 'کھوار'}
    KO = {'full_name': 'Korean', 'short_name': 'ko', 'local_name': '한국어'}
    KR = {'full_name': 'Kanuri', 'short_name': 'kr', 'local_name': 'Kanuri'}
    KS = {'full_name': 'Kashmiri', 'short_name': 'ks', 'local_name': 'कॉशुर / کٲشُر'}
    KSH = {'full_name': 'Ripuarian', 'short_name': 'ksh', 'local_name': 'Ripoarisch'}
    KU = {'full_name': 'Kurdish (Kurmanji)', 'short_name': 'ku', 'local_name': 'Kurdî'}
    KV = {'full_name': 'Komi', 'short_name': 'kv', 'local_name': 'Коми'}
    KW = {'full_name': 'Cornish', 'short_name': 'kw', 'local_name': 'Kernewek'}
    KY = {'full_name': 'Kirghiz', 'short_name': 'ky', 'local_name': 'Kırgızca / Кыргызча'}
    LA = {'full_name': 'Latin', 'short_name': 'la', 'local_name': 'Latina'}
    LAD = {'full_name': 'Ladino / Judeo-Spanish', 'short_name': 'lad', 'local_name': 'Dzhudezmo / Djudeo-Espanyol'}
    LAN = {'full_name': 'Lango', 'short_name': 'lan', 'local_name': 'Leb Lango / Luo'}
    LB = {'full_name': 'Luxembourgish', 'short_name': 'lb', 'local_name': 'Lëtzebuergesch'}
    LG = {'full_name': 'Ganda', 'short_name': 'lg', 'local_name': 'Luganda'}
    LI = {'full_name': 'Limburgian', 'short_name': 'li', 'local_name': 'Limburgs'}
    LIJ = {'full_name': 'Ligurian', 'short_name': 'lij', 'local_name': 'Líguru'}
    LMO = {'full_name': 'Lombard', 'short_name': 'lmo', 'local_name': 'Lumbaart'}
    LN = {'full_name': 'Lingala', 'short_name': 'ln', 'local_name': 'Lingála'}
    LO = {'full_name': 'Laotian', 'short_name': 'lo', 'local_name': 'ລາວ / Pha xa lao'}
    LZZ = {'full_name': 'Laz', 'short_name': 'lzz', 'local_name': 'Lazuri / ლაზური'}
    LT = {'full_name': 'Lithuanian', 'short_name': 'lt', 'local_name': 'Lietuvių'}
    LV = {'full_name': 'Latvian', 'short_name': 'lv', 'local_name': 'Latviešu'}
    MAP_BMS = {'full_name': 'Banyumasan', 'short_name': 'map-bms', 'local_name': 'Basa Banyumasan'}
    MG = {'full_name': 'Malagasy', 'short_name': 'mg', 'local_name': 'Malagasy'}
    MAN = {'full_name': 'Mandarin', 'short_name': 'man', 'local_name': '官話/官话'}
    MH = {'full_name': 'Marshallese', 'short_name': 'mh', 'local_name': 'Kajin Majel / Ebon'}
    MI = {'full_name': 'Māori', 'short_name': 'mi', 'local_name': 'Māori'}
    MIN = {'full_name': 'Minangkabau', 'short_name': 'min', 'local_name': 'Minangkabau'}
    MK = {'full_name': 'Macedonian', 'short_name': 'mk', 'local_name': 'Македонски'}
    ML = {'full_name': 'Malayalam', 'short_name': 'ml', 'local_name': 'മലയാളം'}
    MN = {'full_name': 'Mongolian', 'short_name': 'mn', 'local_name': 'Монгол'}
    MO = {'full_name': 'Moldovan', 'short_name': 'mo', 'local_name': 'Moldovenească'}
    MR = {'full_name': 'Marathi', 'short_name': 'mr', 'local_name': 'मराठी'}
    MRH = {'full_name': 'Mara', 'short_name': 'mrh', 'local_name': 'Mara'}
    MS = {'full_name': 'Malay', 'short_name': 'ms', 'local_name': 'Bahasa Melayu'}
    MT = {'full_name': 'Maltese', 'short_name': 'mt', 'local_name': 'bil-Malti'}
    MUS = {'full_name': 'Creek / Muskogee', 'short_name': 'mus', 'local_name': 'Mvskoke'}
    MWL = {'full_name': 'Mirandese', 'short_name': 'mwl', 'local_name': 'Mirandés'}
    MY = {'full_name': 'Burmese', 'short_name': 'my', 'local_name': 'Myanmasa'}
    NA = {'full_name': 'Nauruan', 'short_name': 'na', 'local_name': 'Dorerin Naoero'}
    NAH = {'full_name': 'Nahuatl', 'short_name': 'nah', 'local_name': 'Nahuatl'}
    NAP = {'full_name': 'Neapolitan', 'short_name': 'nap', 'local_name': 'Nnapulitano'}
    ND = {'full_name': 'North Ndebele', 'short_name': 'nd', 'local_name': 'Sindebele'}
    NDS = {'full_name': 'Low German / Low Saxon', 'short_name': 'nds', 'local_name': 'Plattdüütsch'}
    NDS_NL = {'full_name': 'Dutch Low Saxon', 'short_name': 'nds-nl', 'local_name': 'Nedersaksisch'}
    NE = {'full_name': 'Nepali', 'short_name': 'ne', 'local_name': 'नेपाली'}
    NEW = {'full_name': 'Newar', 'short_name': 'new', 'local_name': 'नेपालभाषा / Newah Bhaye'}
    NG = {'full_name': 'Ndonga', 'short_name': 'ng', 'local_name': 'Oshiwambo'}
    NL = {'full_name': 'Dutch', 'short_name': 'nl', 'local_name': 'Nederlands'}
    NN = {'full_name': 'Norwegian Nynorsk', 'short_name': 'nn', 'local_name': 'Norsk (nynorsk)'}
    NO = {'full_name': 'Norwegian', 'short_name': 'no', 'local_name': 'Norsk (bokmål / riksmål)'}
    NR = {'full_name': 'South Ndebele', 'short_name': 'nr', 'local_name': 'isiNdebele'}
    NSO = {'full_name': 'Northern Sotho', 'short_name': 'nso', 'local_name': 'Sesotho sa Leboa / Sepedi'}
    NRM = {'full_name': 'Norman', 'short_name': 'nrm', 'local_name': 'Nouormand / Normaund'}
    NV = {'full_name': 'Navajo', 'short_name': 'nv', 'local_name': 'Diné bizaad'}
    NY = {'full_name': 'Chichewa', 'short_name': 'ny', 'local_name': 'Chi-Chewa'}
    OC = {'full_name': 'Occitan', 'short_name': 'oc', 'local_name': 'Occitan'}
    OJ = {'full_name': 'Ojibwa', 'short_name': 'oj', 'local_name': 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin'}
    OM = {'full_name': 'Oromo', 'short_name': 'om', 'local_name': 'Oromoo'}
    OR = {'full_name': 'Oriya', 'short_name': 'or', 'local_name': 'ଓଡ଼ିଆ'}
    OS = {'full_name': 'Ossetian / Ossetic', 'short_name': 'os', 'local_name': 'Иронау'}
    PA = {'full_name': 'Panjabi / Punjabi', 'short_name': 'pa', 'local_name': 'ਪੰਜਾਬੀ / پنجابی'}
    PAG = {'full_name': 'Pangasinan', 'short_name': 'pag', 'local_name': 'Pangasinan'}
    PAM = {'full_name': 'Kapampangan', 'short_name': 'pam', 'local_name': 'Kapampangan'}
    PAP = {'full_name': 'Papiamentu', 'short_name': 'pap', 'local_name': 'Papiamentu'}
    PDC = {'full_name': 'Pennsylvania German', 'short_name': 'pdc', 'local_name': 'Deitsch'}
    PI = {'full_name': 'Pali', 'short_name': 'pi', 'local_name': 'Pāli / पाऴि'}
    PIH = {'full_name': 'Norfolk', 'short_name': 'pih', 'local_name': 'Norfuk'}
    PL = {'full_name': 'Polish', 'short_name': 'pl', 'local_name': 'Polski'}
    PMS = {'full_name': 'Piedmontese', 'short_name': 'pms', 'local_name': 'Piemontèis'}
    PS = {'full_name': 'Pashto', 'short_name': 'ps', 'local_name': 'پښتو'}
    PT = {'full_name': 'Portuguese', 'short_name': 'pt', 'local_name': 'Português'}
    QU = {'full_name': 'Quechua', 'short_name': 'qu', 'local_name': 'Runa Simi'}
    RM = {'full_name': 'Raeto Romance', 'short_name': 'rm', 'local_name': 'Rumantsch'}
    RMY = {'full_name': 'Romani', 'short_name': 'rmy', 'local_name': 'Romani / रोमानी'}
    RN = {'full_name': 'Kirundi', 'short_name': 'rn', 'local_name': 'Kirundi'}
    RO = {'full_name': 'Romanian', 'short_name': 'ro', 'local_name': 'Română'}
    ROA_RUP = {'full_name': 'Aromanian', 'short_name': 'roa-rup', 'local_name': 'Armâneashti'}
    RU = {'full_name': 'Russian', 'short_name': 'ru', 'local_name': 'Русский'}
    RW = {'full_name': 'Rwandi', 'short_name': 'rw', 'local_name': 'Kinyarwandi'}
    SA = {'full_name': 'Sanskrit', 'short_name': 'sa', 'local_name': 'संस्कृतम्'}
    SC = {'full_name': 'Sardinian', 'short_name': 'sc', 'local_name': 'Sardu'}
    SCN = {'full_name': 'Sicilian', 'short_name': 'scn', 'local_name': 'Sicilianu'}
    SCO = {'full_name': 'Scots', 'short_name': 'sco', 'local_name': 'Scots'}
    SD = {'full_name': 'Sindhi', 'short_name': 'sd', 'local_name': 'सिंधी / سنڌي‎'}
    SE = {'full_name': 'Northern Sami', 'short_name': 'se', 'local_name': 'Davvisámegiella'}
    SG = {'full_name': 'Sango', 'short_name': 'sg', 'local_name': 'Sängö'}
    SH = {'full_name': 'Serbo-Croatian', 'short_name': 'sh', 'local_name': 'Srpskohrvatski / Српскохрватски'}
    SI = {'full_name': 'Sinhalese', 'short_name': 'si', 'local_name': 'සිංහල'}
    SIMPLE = {'full_name': 'Simple English', 'short_name': 'simple', 'local_name': 'Simple English'}
    SK = {'full_name': 'Slovak', 'short_name': 'sk', 'local_name': 'Slovenčina'}
    SL = {'full_name': 'Slovenian', 'short_name': 'sl', 'local_name': 'Slovenščina'}
    SM = {'full_name': 'Samoan', 'short_name': 'sm', 'local_name': 'Gagana Samoa'}
    SN = {'full_name': 'Shona', 'short_name': 'sn', 'local_name': 'chiShona'}
    SO = {'full_name': 'Somalia', 'short_name': 'so', 'local_name': 'Soomaaliga'}
    SQ = {'full_name': 'Albanian', 'short_name': 'sq', 'local_name': 'Shqip'}
    SR = {'full_name': 'Serbian', 'short_name': 'sr', 'local_name': 'Српски'}
    SS = {'full_name': 'Swati', 'short_name': 'ss', 'local_name': 'SiSwati'}
    ST = {'full_name': 'Southern Sotho', 'short_name': 'st', 'local_name': 'Sesotho'}
    SU = {'full_name': 'Sundanese', 'short_name': 'su', 'local_name': 'Basa Sunda'}
    SV = {'full_name': 'Swedish', 'short_name': 'sv', 'local_name': 'Svenska'}
    SW = {'full_name': 'Swahili', 'short_name': 'sw', 'local_name': 'Kiswahili'}
    TA = {'full_name': 'Tamil', 'short_name': 'ta', 'local_name': 'தமிழ்'}
    TE = {'full_name': 'Telugu', 'short_name': 'te', 'local_name': 'తెలుగు'}
    TET = {'full_name': 'Tetum', 'short_name': 'tet', 'local_name': 'Tetun'}
    TG = {'full_name': 'Tajik', 'short_name': 'tg', 'local_name': 'Тоҷикӣ'}
    TH = {'full_name': 'Thai', 'short_name': 'th', 'local_name': 'ไทย / Phasa Thai'}
    TI = {'full_name': 'Tigrinya', 'short_name': 'ti', 'local_name': 'ትግርኛ'}
    TK = {'full_name': 'Turkmen', 'short_name': 'tk', 'local_name': 'Туркмен / تركمن'}
    TL = {'full_name': 'Tagalog', 'short_name': 'tl', 'local_name': 'Tagalog'}
    TLH = {'full_name': 'Klingon', 'short_name': 'tlh', 'local_name': 'tlhIngan-Hol'}
    TN = {'full_name': 'Tswana', 'short_name': 'tn', 'local_name': 'Setswana'}
    TO = {'full_name': 'Tonga', 'short_name': 'to', 'local_name': 'Lea Faka-Tonga'}
    TPI = {'full_name': 'Tok Pisin', 'short_name': 'tpi', 'local_name': 'Tok Pisin'}
    TR = {'full_name': 'Turkish', 'short_name': 'tr', 'local_name': 'Türkçe'}
    TS = {'full_name': 'Tsonga', 'short_name': 'ts', 'local_name': 'Xitsonga'}
    TT = {'full_name': 'Tatar', 'short_name': 'tt', 'local_name': 'Tatarça'}
    TUM = {'full_name': 'Tumbuka', 'short_name': 'tum', 'local_name': 'chiTumbuka'}
    TW = {'full_name': 'Twi', 'short_name': 'tw', 'local_name': 'Twi'}
    TY = {'full_name': 'Tahitian', 'short_name': 'ty', 'local_name': 'Reo Mā`ohi'}
    UDM = {'full_name': 'Udmurt', 'short_name': 'udm', 'local_name': 'Удмурт кыл'}
    UG = {'full_name': 'Uyghur', 'short_name': 'ug', 'local_name': 'Uyƣurqə / ئۇيغۇرچە'}
    UK = {'full_name': 'Ukrainian', 'short_name': 'uk', 'local_name': 'Українська'}
    UR = {'full_name': 'Urdu', 'short_name': 'ur', 'local_name': 'اردو'}
    UZ = {'full_name': 'Uzbek', 'short_name': 'uz', 'local_name': 'Ўзбек'}
    UZ_AF = {'full_name': 'Uzbeki Afghanistan', 'short_name': 'uz_AF', 'local_name': 'اوزبیکی'}
    VE = {'full_name': 'Venda', 'short_name': 've', 'local_name': 'Tshivenḓa'}
    VI = {'full_name': 'Vietnamese', 'short_name': 'vi', 'local_name': 'Việtnam'}
    VEC = {'full_name': 'Venetian', 'short_name': 'vec', 'local_name': 'Vèneto'}
    VLS = {'full_name': 'West Flemish', 'short_name': 'vls', 'local_name': 'West-Vlaoms'}
    VO = {'full_name': 'Volapük', 'short_name': 'vo', 'local_name': 'Volapük'}
    WA = {'full_name': 'Walloon', 'short_name': 'wa', 'local_name': 'Walon'}
    WAR = {'full_name': 'Waray / Samar-Leyte Visayan', 'short_name': 'war',
           'local_name': 'Winaray / Binisaya Lineyte-Samarnon'}
    WO = {'full_name': 'Wolof', 'short_name': 'wo', 'local_name': 'Wollof'}
    XAL = {'full_name': 'Kalmyk', 'short_name': 'xal', 'local_name': 'Хальмг'}
    XH = {'full_name': 'Xhosa', 'short_name': 'xh', 'local_name': 'isiXhosa'}
    XMF = {'full_name': 'Megrelian', 'short_name': 'xmf', 'local_name': 'მარგალური'}
    YI = {'full_name': 'Yiddish', 'short_name': 'yi', 'local_name': 'ייִדיש'}
    YO = {'full_name': 'Yoruba', 'short_name': 'yo', 'local_name': 'Yorùbá'}
    ZA = {'full_name': 'Zhuang', 'short_name': 'za', 'local_name': 'Cuengh / Tôô / 壮语'}
    ZH = {'full_name': 'Chinese', 'short_name': 'zh', 'local_name': '中文'}
    ZH_CLASSICAL = {'full_name': 'Classical Chinese', 'short_name': 'zh-classical', 'local_name': '文言'}
    ZH_MIN_NAN = {'full_name': 'Minnan', 'short_name': 'zh-min-nan', 'local_name': 'Bân-lâm-gú'}
    ZH_YUE = {'full_name': 'Cantonese', 'short_name': 'zh-yue', 'local_name': '粵語 / 粤语'}
    ZU = {'full_name': 'Zulu', 'short_name': 'zu', 'local_name': 'isiZulu'}
